use [mindr-live]
go 


if exists(select o.name from sysobjects o where o.name='mpf_mv')
begin 
drop view mpf_mv
end 
go 

Create view mpf_mv as 
SELECT
mp.uid,
tlpin,
sector,
hhid,
hhchange,
newhhid,
womname,
husbname,
jw.jivitaweek as mpwkint,
convert(smalldatetime, mp.mpdate,121) as mpdate,
workerid,
mpstatus,
convert(smalldatetime,mpdoc,121) as mpdoc,
convert(smalldatetime,mpdod,121) as mpdod,
/*secc*/
mpcgh30,
mpcgh30d,
mpcghtx1,
mpcghtx2,
mpcgh7,
mpcgh7n,
mpbrth30,
mpbrth30d,
mpbrthtx1,
mpbrthtx2,
mpbrth7,
mpbrth7n,
mpappt30,
mpappt30d,
mpappttx1,
mpappttx2,
mpappt7,
mpnaus30,
mpnaus30d,
mpnaustx1,
mpnaustx2,
mpnaus7,
mpvmt30,
mpvmt30d,
mpvmttx1,
mpvmttx2,
mpvmt7,
mpconv30,
mpconv30d,
mpconvtx1,
mpconvtx2,
mpconv7,
mpconv7n,
mpswlh30,
mpswlh30d,
mpswlhtx1,
mpswlhtx2,
mpswlh7,
mpswlh7n,
mpswlf30,
mpswlf30d,
mpswlftx1,
mpswlftx2,
mpswlf7,
mpswlf7n,
mphach30,
mphach30d,
mphachtx1,
mphachtx2,
mphach7,
mphach7n,
mphfvr30,
mphfvr30d,
mphfvrtx1,
mphfvrtx2,
mphfvr7,
mphfvr7n,
mplfvr30,
mplfvr30d,
mplfvrtx1,
mplfvrtx2,
mplfvr7,
mpdiar30,
mpdiar30d,
mpdiartx1,
mpdiartx2,
mpdiar7,
mpdiar7n,
mpdys30,
mpdys30d,
mpdystx1,
mpdystx2,
mpdys7,
mpdys7n,
mpwdys30,
mpwdys30d,
mpwdystx1,
mpwdystx2,
mpwdys7,
mplabd30,
mplabd30d,
mplabdtx1,
mplabdtx2,
mplabd7,
mplabd7n,
mpurin30,
mpurin30d,
mpurintx1,
mpurintx2,
mpurin7,
mpurin7n,
mpvagd30,
mpvagd30d,
mpvagdtx1,
mpvagdtx2,
mpvagd7,
mpvagd7n,
mpspot30,
mpspot30d,
mpspottx1,
mpspottx2,
mpspot7,
mpspot7n,
mpvbld30,
mpvbld30d,
mpvbldtx1,
mpvbldtx2,
mpvbld7,
mpvbld7n,
mpxn30,
mpxn30d,
mpxntx1,
mpxntx2,
mpxn7,
mpxn7n,
/*secd*/
version,
today,
start,
[end],
scheduleid,
submm,
subyy,
todaymmyy,
idenconf,
insert_time,
update_time,
inserted_by,
updateed_by,
mp._submission_time,
_submitted_by,
_date_modified,
_xform_id,
instance_id,
_duration,
_media_all_received,
_media_count,
_id,
_uuid,
_version,
duplicate
from [mindr-live].dbo.all_mpf mp
join shapla.dbo.JiVitAWeek jw on jw.RomanDate = convert(smalldatetime,mp.mpdate,121)
left join 
(select b.uid,b.mpdate,max(b._submission_time) _submission_time
from (select mp1.uid,mp1.mpdate,_submission_time from [mindr-live].dbo.all_mpf mp1
left join (select mp2.uid, max(mpdate) mpdate 
from [mindr-live].dbo.all_mpf mp2
where duplicate is null
group by mp2.uid) a on a.uid = mp1.uid and mp1.mpdate =a.mpdate where a.mpdate is not null
and mp1.duplicate is null 

) b group by b.uid,b.mpdate) c on c.uid = mp.uid  and c.mpdate = mp.mpdate and c._submission_time = mp._submission_time 
where mp.duplicate is null and c.uid is not null                  
